### ISSUE TITLE
Hotkey for quickly searching Dash from within Xcode

### ISSUE THREAD

**Issue by quiekedei** [Kapeli/Dash-Alfred-Workflow#10]
Hi there!

Since the [Dash plugin for Xcode](https://github.com/omz/Dash-Plugin-for-Xcode) no longer works in Xcode 8 and above, I was looking for a way to quickly and precisely search Apple docsets from within Xcode. I know that the currently suggested way to do this is to use a _Global Search Shortcut_ but to me this does not really do the trick. Especially when it comes to looking up methods with parameters a simple text selection does not really play well with Dash.

A possible solution I came up with would be to use Xcode's _Copy Symbol Name_ functionality and feed the result into a Dash query. I whipped up a quick workflow, which uses your `dashAlfredWorkflow` script. Would you be interested in integrating this functionality in this workflow? If so, I could open a PR. If not, would it be alright to use the `dashAlfredWorkflow` script in a standalone workflow?

**Comment by Kapeli** [comment]
I think this would be outside of the scope of the Alfred workflow.

If you can, please make your workflow use the `dashAlfredWorkflow` within Dash.app (located at `Dash.app/Contents/Resources/dashAlfredWorkflow`). This ensures you're using the latest version.

If that's not possible, it's ok to just distribute the `dashAlfredWorkflow` yourself.
