### ISSUE TITLE
Add to search fallback?

### ISSUE THREAD

**Issue by gandalfsaxe** [Kapeli/Dash-Alfred-Workflow#11]
Is there an easy way to add Dash to the list of default search fallbacks?

**Comment by Kapeli** [comment]
What do you mean by default search fallback? Where do you want to add Dash exactly?

**Comment by gandalfsaxe** [comment]
adding Dash to this list:

![image](https://user-images.githubusercontent.com/12127864/37553608-d6e55a28-29cb-11e8-89bd-3d99c2e7f9ea.png)

They can be set in Features -> Default Results -> Setup fallback results.

To be honest, I would probably not use it often in practice, but still wouldn't hurt to have as a fallback as well.

**Comment by Kapeli** [comment]
Ah. I see.

You need to add a web search that contains Dash's URL scheme. See https://kapeli.com/dash_plugins for info on the URL scheme.

**Comment by gandalfsaxe** [comment]
Thanks.
