### ISSUE TITLE
Search by docset name without searching by entry

### ISSUE THREAD

**Issue by snoblenet** [Kapeli/Dash-Alfred-Workflow#14]
Sometimes I want to just open the `README.md` for a package like the Github docset for SurfingKeys without knowing the name of any entries that might be defined within the docset, if there are in fact any entries therein.

So I'll type `dash surfingkeys` into Alfred, but nothing comes up.

Is it possible to add any matching docsets (and search groups) to the search results?

**Comment by Kapeli** [comment]
What do you mean by surfingkeys? Which repo exactly?

It works for me for brookhong/surfingkeys. See screenshot.

<img width="646" alt="screenshot 2018-11-29 at 22 01 37" src="https://user-images.githubusercontent.com/1445635/49248449-6546bc00-f422-11e8-9a7c-ba3ee68821fc.png">

**Comment by snoblenet** [comment]
Strange. The top result shown above was not appearing for me before. It is appearing for me now, but as the fourth or so entry.
