### ISSUE TITLE
Ability to open matches in web browser not Dash browser

### ISSUE THREAD

**Issue by snoblenet** [Kapeli/Dash-Alfred-Workflow#15]
It would be awesome if Dash-Alfred-Workflow had the ability to open results directly in the default web browser rather than the Dash browser. (Currently I open them in Dash and them immediately press command-B.)

**Comment by Kapeli** [comment]
If you hold down CMD when you press Enter in Alfred, the result opens in the browser. You can customize the Alfred workflow to have this as the default. Check what the workflow does when the CMD modifier is pressed.
