### ISSUE TITLE
How do I make Dash open page in new tab by default?

### ISSUE THREAD

**Issue by tddschn** [Kapeli/Dash-Alfred-Workflow#18]
It seems that Dash opens up search result page in the current tab. 

How do I change that and make Dash open page in new tab by default? Thanks!

**Comment by Kapeli** [comment]
This is not currently supported, sorry.

**Comment by tddschn** [comment]
Thanks for your reply :)

**Comment by arimorgan** [comment]
Hi, while its not supported as a default, is it supported at all? It seems ctr/command click doesn't work. Wondering if there is another shortcut/option I am missing.

**Comment by Kapeli** [comment]
It's not supported at all.
