### ISSUE TITLE
rubygems has a confusing title, gems not indexed individually

### ISSUE THREAD

**Issue by dkarter** [Kapeli/Dash-Alfred-Workflow#2]
I have a few gem docsets installed in Dash: 
![image](https://cloud.githubusercontent.com/assets/551858/16050140/1aa6d8fe-3220-11e6-90bb-715234d6f166.png)

But when I try to search for capybara documentation:

![image](https://cloud.githubusercontent.com/assets/551858/16050169/3b495c6c-3220-11e6-9c1c-ad0fa3ff12b4.png)

the most natural thing to do is to start searching by typing the name of the gem you want documentation for.

If I type `ruby` in Alfred I get this:

![image](https://cloud.githubusercontent.com/assets/551858/16050213/6a019682-3220-11e6-9ae1-8d512f216251.png)

When select the `rest-client` and type my search query for Capybara I get the result I'm looking for:

![image](https://cloud.githubusercontent.com/assets/551858/16050285/ae0253f8-3220-11e6-9353-8e741ee76796.png)

### Proposed solution:

I think it would be better to have the rubygems title be `rubygems` or simply `gems` and perhaps consider creating a keyword for each gem installed to make it more intuitive to search for help and filter to a specific gem.

**Comment by Kapeli** [comment]
You can change the keywords to anything you want in Preferences > Docsets. See https://kapeli.com/dash_guide#docsetKeywords.

The default for Ruby gem docsets is to use the same keyword for all because that's what most users want.

**Comment by dkarter** [comment]
Works great! I had to re-add the alfred extension after updating.
Thank you!
