### ISSUE TITLE
Keyword doc set search not working in Alfred (some docsets)

### ISSUE THREAD

**Issue by johnathanz** [Kapeli/Dash-Alfred-Workflow#20]
Hi there

I have the following Docsets with keywords set up:

![CleanShot 2021-06-04 at 16 52 24](https://user-images.githubusercontent.com/1593039/120758615-6443f780-c555-11eb-8790-1105ce97ef82.png)

All keywords work, except for `Bash` (Main DocSet) and `GameMaker Studio 2` (User contrib, one that I built myself)

Here's a gif showing what I mean:

![Dash Alfred keyword not working](https://user-images.githubusercontent.com/1593039/120759229-298e8f00-c556-11eb-9de5-2baab127470f.gif)

`Dash` keyword does work for all docsets including `Bash` and `GameMaker Studio 2`, but results are too numerous for common keywords.

Anything specific I needed to do to set up the keywords for those 2 docsets?

Thanks in advance!

**Comment by Kapeli** [comment]
Have you tried to re-import the workflow from Dash's Preferences > Integration?

**Comment by johnathanz** [comment]
Thanks @Kapeli . That fixed it!
