### ISSUE TITLE
Can I use this to search from command line somehow? For use in a new Neovim plugin

### ISSUE THREAD

**Issue by mrjones2014** [Kapeli/Dash-Alfred-Workflow#23]
I'd like to make a new Neovim plugin (the existing Vim plugin hasn't been updated in years and is somewhat limited).

I want to make a Dash plugin that integrates with [Telescope.nvim](https://github.com/nvim-telescope/telescope.nvim). Is there a way to search Dash and get search suggestions/completions on the command line?

**Comment by Kapeli** [comment]
Use the `dashAlfredWorkflow` command line tool inside `Dash.app/Contents/Resources` like this:

```
dashAlfredWorkflow <query>
```

**Comment by mrjones2014** [comment]
@Kapeli is there any documentation on the XML schema that is returned?

**Comment by Kapeli** [comment]
https://www.alfredapp.com/help/workflows/inputs/script-filter/xml/

**Comment by mrjones2014** [comment]
@Kapeli  can I not use the `uid` to open the item? When I do `open` with the `uid` I get this:

![CleanShot-2021-09-24-at-08 01 59](https://user-images.githubusercontent.com/8648891/134670949-852705b3-9178-4944-937d-82cc9892f7ec.png)

**Comment by mrjones2014** [comment]
I got it working! Feel free to list on the site as another integration if you'd like!

https://github.com/mrjones2014/dash.nvim

**Comment by Kapeli** [comment]
Great. I'll add it.
