### ISSUE TITLE
Alfred search immediately overrides the tab search

### ISSUE THREAD

**Issue by katerlouis** [Kapeli/Dash-Alfred-Workflow#3]
I almost exclusively use Dash with Alfred.

When I type in a command the activatd tab in Dash gets overwritten with the new search.
This is bugging me for years now!

Suggestions:

1) Searching with Alfred opens a new tab and searchs there (Don't like this one)

2) Alfred doesn't search inside the Dash-App until I hit Enter; It then would always open a new Tab, unless I press CMD+Enter.

What do you say?

**Comment by Kapeli** [comment]
This is planned, but I have no idea when I'll get to it.

I'm going to close this issue as it's really a feature in Dash which would affect all plugins, and not specific to the Alfred one.
