### ISSUE TITLE
Is it possible to assign a hotkey to a Dash profile?

### ISSUE THREAD

**Issue by nikitavoloboev** [Kapeli/Dash-Alfred-Workflow#4]
That is I press a hotkey and I only search a specific profile.

I know I can search with a prefix like 's: ' or even make this in Alfred : 

![2017-07-01 at 20 01](https://user-images.githubusercontent.com/6391776/27764369-38268f0a-5e98-11e7-929e-a11e6c33ff32.png)

But I want to create a hotkey that will give me a clean Dash alfred prompt like this : 

![2017-07-01 at 20 00](https://user-images.githubusercontent.com/6391776/27764361-ea95607c-5e97-11e7-9d96-8fbd7779e1a8.png)

But the search will be scoped to some profile.

Can I do this?

**Comment by Kapeli** [comment]
You need to edit the Dash Alfred workflow and add a Hotkey trigger which is connected to the search profile you want.
