### ISSUE TITLE
haskell docset keyword isn't detected

### ISSUE THREAD

**Issue by larrybotha** [Kapeli/Dash-Alfred-Workflow#6]
I'm not sure if it's the docset itself, but changing the docset keyword seems to have no effect either

**Comment by Kapeli** [comment]
Have you tried to reinstall the docset?

**Comment by larrybotha** [comment]
ye I did, both when I opened the issue and just now again (to double-check)

**Comment by Kapeli** [comment]
Can you try to reinstall the Alfred workflow as well? Remove it from Alfred, then add it back from Dash's Preferences > Integration.

**Comment by larrybotha** [comment]
ermagerd it works! Didn't think to uninstall the workflow.

The speed of your response feels automated O.o

Thanks for the help! :)
