### ISSUE TITLE
'&' symbol in quicklookurl field not escaped

### ISSUE THREAD

**Issue by tete1030** [Kapeli/Dash-Alfred-Workflow#9]
When I type "git branch"(I'm using the git cheatsheet) in Alfred, it raises an "XML Parsing Error" as shown in the following image.

![image](https://user-images.githubusercontent.com/4312115/29748664-4d580cfe-8ae0-11e7-9964-1046ece23323.png)

The "Row 1, Col 826" refers to a '&' symbol in the XML document output by dashAlfredWorkflow. After prettifying the output, I fount this '&' symbol is in the quicklookurl field.  

![image](https://user-images.githubusercontent.com/4312115/29748665-526f2c72-8ae0-11e7-90f3-6570c2b2a7f8.png)

**Comment by Kapeli** [comment]
Thanks for letting me know about this. It'll be fixed in the next Dash update.
